name: Client Angular

on: [push]

jobs:
  ng-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies (npm ci)
      run: npm ci
      working-directory: ./client
      env:
        CYPRESS_INSTALL_BINARY: 0

    - name: Test (npm run test)
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: ./client

  ng-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies (npm ci)
      run: npm ci
      working-directory: ./client
      env:
        CYPRESS_INSTALL_BINARY: 0

    - name: Lint (npm run lint)
      run: npm run lint
      working-directory: ./client
