name: End-to-End

on: [push]

jobs:
  ng-e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle artifacts (downloaded JARs, the wrapper, and any downloaded JDKs)
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/jdks
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle/') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Run e2e tests
      uses: cypress-io/github-action@v2
      with:
        start: ${{ github.workspace }}/server/gradlew run -p ${{ github.workspace }}/server/
        command: npm run e2e
        working-directory: ./client


